version: '3.8'

services:
  # MySQL database service
  db:
    image: mysql:8.0
    container_name: taskdb
    environment:
      MYSQL_ROOT_PASSWORD: codewarx   # Set your MySQL root password here
      MYSQL_DATABASE: task  # Name of the database to create
      MYSQL_USER: codewarrior  # MySQL user
      MYSQL_PASSWORD: codewarx  # MySQL user password
    ports:
      - "3306:3306"  # Expose MySQL port (on your host machine)
    volumes:
      - mysql-data:/var/lib/mysql  # Persist data across container restarts

  # Your Go application service (app will be connected to db)
  app:
    build:
      context: .
      dockerfile: Dockerfile  # This is your existing Dockerfile for your app
    container_name: taskapp
    ports:
      - "4023:4023"  # Expose your app port
    environment:
      - DB_HOST=db  # Connect to db service
      - DB_PORT=3306
      - DB_USER=codewarrior
      - DB_PASS=codewarx
      - DB_NAME=task
    depends_on:
      - db  # Ensure db starts before your app

volumes:
  mysql-data:
    driver: local
